### ISSUE TITLE
Creating DB CRD without annotations causes panic

### ISSUE THREAD

**Issue by mdrakiburrahman** [pplavetzki/azure-sql-mi#1]
_Hi @pplavetzki  - just logging here for tracking purposes_

I noticed when you create a Database CRD in the following format, without annotations - the Operator throws up a panic error in [this line](https://github.com/pplavetzki/azure-sql-mi/blob/f422d8833bd848524984e1d975d808d91b018df9/controllers/database_controller.go#L60) when you apply the CR, and after it Creates the Database in SQL MI (see screenshot):

```yaml
apiVersion: actions.msft.isd.coe.io/v1alpha1
kind: Database
metadata:
  name: database-rbc1
  # Notice no annotations
spec:
  name: contosoHR
  server: 13.72.81.14
  port: 1433
  collationName: SQL_Latin1_General_CP1_CS_AS
  sqlManagedInstance: jumpstart-sql
  credentials:
    name: credentials
    passwordKey: ArcPassword123!!
    usernameKey: arcdemo
```
Panic: 
`panic: assignment to entry in nil map`
![image](https://user-images.githubusercontent.com/46581776/133004627-434e93b4-6578-40b5-982b-232e2ed47bb3.png)

Given the `nil` error, I thought this is because the CR is getting created (by the user) without any `annotations` (which is valid) - so perhaps that's why `annotations["mssql/db_id"] = a.DatabaseID` is throwing a `nil map` error.

To test this - I created with this CR instead:
```yaml
apiVersion: actions.msft.isd.coe.io/v1alpha1
kind: Database
metadata:
  name: database-rbc1
  annotations:    # Added in
    creator: raki   # Added in
spec:
  name: contosoHR
  server: 13.72.81.14
  port: 1433
  collationName: SQL_Latin1_General_CP1_CS_AS
  sqlManagedInstance: jumpstart-sql
  credentials:
    name: credentials
    passwordKey: ArcPassword123!!
    usernameKey: arcdemo
```
This gets past panic and successfully completes the first pass of the reconcile:
![image](https://user-images.githubusercontent.com/46581776/133004750-b4c52107-6134-44fb-9e6d-829035bb5bb5.png)

The simple changes made above are in this fork: https://github.com/mdrakiburrahman/azure-sql-mi/commit/73c464e3a7d6d20ac7bce77495e24bac0b05a2e1

Instead of having the user creating the DB CR with annotations, perhaps it would be best if there's a way to set the logic in the controller to catch this error?
